### PR TITLE
test: require symlinked binary module twice

### PR DESCRIPTION
**Pull request by saper**
Attempt to load the binary module disguised
behind two symlinked locations.

Big thanks to Michael Mifsud <xzyfer@gmail.com>
for preparing a proper test case.

### CODE REVIEW

**Comment by jasnell** [comment]
Getting an error when attempting to run this:

```
    throw err;
    ^

Error: Cannot find module '/Users/james/Node/main/node/test/tmp.0/second/binding.node'
    at Function.Module._resolveFilename (module.js:429:15)
    at Function.Module._load (module.js:377:25)
    at Module.require (module.js:457:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/james/Node/main/node/test/addons/symlinked-module/submodule.js:7:11)
    at Module._compile (module.js:532:32)
    at Object.Module._extensions..js (module.js:541:10)
    at Module.load (module.js:447:32)
    at tryModuleLoad (module.js:406:12)
    at Function.Module._load (module.js:398:3)
Command: out/Release/node /Users/james/Node/main/node/test/addons/symlinked-module/submodule.js
```

Doing a make clean with a fresh test/tmp* to try again.

**Comment by jasnell** [comment]
```
/Applications/Xcode.app/Contents/Developer/usr/bin/make lint
./node tools/jslint.js -J benchmark lib src test tools/doc \
          tools/eslint-rules tools/jslint.js
[00:03|% 58|+   196|-     0]: test        
/Users/james/Node/main/node/test/addons/symlinked-module/test.js
  14:5  error  Expected indentation of 2 space characters but found 4  indent
  16:5  error  Expected indentation of 2 space characters but found 4  indent
  17:5  error  Expected indentation of 2 space characters but found 4  indent
  32:5  error  'tertiary' is defined but never used                    no-unused-vars

✖ 4 problems (4 errors, 0 warnings)

[00:05|%100|+  1508|-     1]: Done
make[1]: *** [jslint] Error 1
make[1]: *** Waiting for unfinished jobs....
Total errors found: 0
make: *** [test] Error 2
bash-3.2$ make -j8 test-addons
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C out BUILDTYPE=Release V=1
make[1]: Nothing to be done for `all'.
ln -fs out/Release/node node
/usr/bin/python tools/test.py --mode=release addons
=== release submodule ===                    
Path: addons/symlinked-module/submodule
module.js:431
    throw err;
    ^

Error: Cannot find module '/Users/james/Node/main/node/test/tmp.0/second/binding.node'
    at Function.Module._resolveFilename (module.js:429:15)
    at Function.Module._load (module.js:377:25)
    at Module.require (module.js:457:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/james/Node/main/node/test/addons/symlinked-module/submodule.js:7:11)
    at Module._compile (module.js:532:32)
    at Object.Module._extensions..js (module.js:541:10)
    at Module.load (module.js:447:32)
    at tryModuleLoad (module.js:406:12)
    at Function.Module._load (module.js:398:3)
Command: out/Release/node /Users/james/Node/main/node/test/addons/symlinked-module/submodule.js
[00:08|% 100|+  27|-   1]: Done                                                
make: *** [test-addons] Error 1
```

**Comment by jasnell** [comment]
```
/Applications/Xcode.app/Contents/Developer/usr/bin/make lint
./node tools/jslint.js -J benchmark lib src test tools/doc \
          tools/eslint-rules tools/jslint.js
[00:03|% 58|+   196|-     0]: test        
/Users/james/Node/main/node/test/addons/symlinked-module/test.js
  14:5  error  Expected indentation of 2 space characters but found 4  indent
  16:5  error  Expected indentation of 2 space characters but found 4  indent
  17:5  error  Expected indentation of 2 space characters but found 4  indent
  32:5  error  'tertiary' is defined but never used                    no-unused-vars

✖ 4 problems (4 errors, 0 warnings)

[00:05|%100|+  1508|-     1]: Done
make[1]: *** [jslint] Error 1
make[1]: *** Waiting for unfinished jobs....
Total errors found: 0
make: *** [test] Error 2
bash-3.2$ make -j8 test-addons
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C out BUILDTYPE=Release V=1
make[1]: Nothing to be done for `all'.
ln -fs out/Release/node node
/usr/bin/python tools/test.py --mode=release addons
=== release submodule ===                    
Path: addons/symlinked-module/submodule
module.js:431
    throw err;
    ^

Error: Cannot find module '/Users/james/Node/main/node/test/tmp.0/second/binding.node'
    at Function.Module._resolveFilename (module.js:429:15)
    at Function.Module._load (module.js:377:25)
    at Module.require (module.js:457:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/james/Node/main/node/test/addons/symlinked-module/submodule.js:7:11)
    at Module._compile (module.js:532:32)
    at Object.Module._extensions..js (module.js:541:10)
    at Module.load (module.js:447:32)
    at tryModuleLoad (module.js:406:12)
    at Function.Module._load (module.js:398:3)
Command: out/Release/node /Users/james/Node/main/node/test/addons/symlinked-module/submodule.js
[00:08|% 100|+  27|-   1]: Done                                                
make: *** [test-addons] Error 1
```

**Comment by saper** [comment]
probably fixed in my master.

Lost of tests fail badly on my clean VS2013 installation, is this a normal state of the node's CI on Windows?

**Comment by jasnell** [comment]
Ok, got this in, had to make a couple of edits to get it working. Thank you very much.

**Pull request closed without merging**
